### PR TITLE
Added 3-perf implementation

### PR DESCRIPTION
**Pull request by iluvcapra**
Needs more tests but this implements the feature.

See also  at 548 in timecode.rs for a general algorithm for calculating footage representations for any mix of perfs and gauge.

### CODE REVIEW

**Comment by iluvcapra** [comment]
Hey just curious if there was anything I could do to fix this? I opened this up again the other day and ended up rewriting it, forgetting that I'd submitted this PR!

**Comment by iluvcapra** [comment]
Just went ahead and added 35mm 2p and 16mm.

**Comment by peake100** [comment]
Hey!

Thank you for your interest!

I unfortunately don't have the time right now to actively maintain this repo. It was always just kind of a for-fun repo to help me learn Rust. Timecode is one of those problems I know pretty well, so I often write a TC library to help me learn a language.

I'm glad this library seems to have found some use. If you would like to maintain a Rust TC library, feel free to fork this. I'd just ask you give me credit in your README somewhere, but this is MIT licensed so the request is just for courtesy. If I were to take a second pass at this repo in the future I would probably base the Rational values on some sort of Big Int implementation rather than kicking things up to 128-bit and hoping for the best, haha. Or just make the whole thing a generic and let people supply their int-size of choice.

One thing to call out, for if I have time in the future to return to this:

The way I have this repo set up is that PR's should be based on dev, then target dev. There's a bunch of files in your PR that get generated by CI before it is committed to main that makes me think you based your branch off main. I'd definitely ask you to re-make this PR based off dev before I reviewed it.

Thanks again!

**Comment by iluvcapra** [comment]
Let me submit a new PR, I think I've fixed it.

**Pull request closed without merging**
