### PR TITLE
Threeperf feature

### PR DESCRIPTION
**Pull request by iluvcapra**
Seeing if I did the rebase correctly.

### CODE REVIEW

**Comment by peake100** [comment]
Apologies for the long delay, got distracted by work proper and some health stuff.

This PR looks great and I really appreciate the effort. The only thing I would ask is that you add some additional tests for the new formats.

Look through my table tests and add an entry for each that puts the new formats. I think that should give pretty good coverage and we can merge this on up.

**Comment by peake100** [comment]
Also I'm noticing this PR is still against main but should be against dev.

I need to add a section about contributing. You aren't the only one making PRs based on main in these repos. Sorry for the trouble!

**Comment by iluvcapra** [comment]
I'll try to fix this later.

**Comment by iluvcapra** [comment]
I've re-posed this (now based on dev) as PR #8.

**Pull request closed without merging**
